---
# Source: ui/templates/configmap-xml.yaml
apiVersion: v1
kind: ConfigMap
metadata:
 name: react-ui-config-xml
 labels:
  app:
    app: react-ui
    env: qa
data:
  app.xml: |
  
    <receivers>
      <topic>
        <options type="receiver">
          <option name="ordered_delivery" order="deny,allow">
            <deny>0</deny>
          </option>
        </options>
      </topic>
    </receivers>
---
# Source: ui/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
 name: react-ui-config
 labels:
  app:
    app: react-ui
    env: qa
data:
 config.yaml: |
    database:
      ip: 120.20.30.40
      name: ui-qa
    logfile: /app/var/log.txt
    timeout: 5s
---
# Source: ui/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ui-service
  labels:
    app: react-ui
    env: qa
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: react-ui
  type: NodePort
---
# Source: ui/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-ui-dep
  labels:
    app: react-ui
    env: qa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-ui
  template:
    metadata:
      labels:
        app: react-ui
        env: qa
    spec:
      containers:
        - name: react-ui
          image: deekshithsn/ui
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 1
              memory: 2Gi
